CUSTMASTL1.FILE: custmastl1.lf CUSTMAST.FILE
ITEMMAST.FILE: itemmast.pf
CUSTMAST.FILE: custmast.pf
ORDERITEM.FILE: orderitem.pf
ITEMMASTL1.FILE: itemmastl1.lf ITEMMAST.FILE
ORDERITML1.FILE: orderitml1.lf ORDERITEM.FILE